spring:
  datasource:
    url:
    driver-class-name:
    username:
    password:
  jpa:
    database-platform:
  h2:
    console:
      enabled: false
  security:
    user:
      name: admin
      password: $)<WV.;m7df:8$Dp{L-v\t
  boot:
    admin:
      client:
        instance:
          metadata:
            tags:
              environment: local